version: '2'
services:
    atm-namingserver:
        container_name: atm-namingserver
        
        image: navneet204/atm-namingserver:cloudnative
        ports:
            - 8761:8761
        networks:
            - spring-cloud-network
    atm-gateway:
        container_name: atm-gateway
       
        image: navneet204/atm-gateway:cloudnative
        ports:
            - 8766:8766
        networks:
            - spring-cloud-network
    atm-api:
        container_name: atm-api
        
        image: navneet204/atm-api:cloudnative
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
    atm-client:
        container_name: atm-client
        
        image: navneet204/atm-client:cloudnative
        ports:
            - 8181:8181
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge